
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

documents.page_size = 6
jwt.secret=DayLaChuoiBaoMatCuaThuVienSoThongMinhNhomChungTa2024DT3KhongDuocGhiCungTrongSourceCode
jwt.expiration=86400000